site_name: "mdv"
site_description: "Terminal Markdown & HTML Viewer"
site_url: "https://github.com/AXGKl/terminal_markdown_viewer"
repo_url: "https://github.com/AXGKl/terminal_markdown_viewer"
repo_name: "axiros/terminal_markdown_viewer"

copyright: |
  Copyright &copy; Gunther Klessinger

nav:
  - Overview: index.md
  - Usage:
      - Styling: usage/css.md
      - Shorthands: usage/css_shorthands.md
      - Colors: usage/colors.md
      - Terminal Control Sequences Primer: usage/ansi.md
  - Dev:
      - Mechanics: dev/plugins.md
  - Version 1:
      - Readme: v1/index.md
  - About:
      - Changelog: about/changelog.md
      - Credits: about/credits.md
      - Contributing: dev/contributing.md
      - Todo: about/todo.md

theme:
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.sections
      #- toc.integrate
    - navigation.expand
  name: material
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: preference
    primary: orange
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
    #- toc.autohide

markdown_extensions:
  - admonition
  - attr_list # {: style="height: ..."}
  - footnotes # foo[^1] is ...(start with ^)
  - meta
  - markdown_include.include
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - markdown.extensions.tables
  - markdown.extensions.footnotes
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
  - toc:
      permalink: "¤"
  - pymdownx.snippets:
      base_path:
        - docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/axiros

plugins:
  # in this order. e.g. md-replace before lp, so that lp can process its results
  - search
  - lcd-blacklist
  - lcd-md-replace
  - lcd-lp
  - lcd-find-pages:
      find-pages:
        - dev/plugs/
  - lcd-page-tree
  - lcd-stats
  - macros:
      j2_block_start_string: "<%{"
      j2_block_end_string: "}%>"
      j2_variable_start_string: "<{"
      j2_variable_end_string: "}>"
