{'cee9b6e6dad2f1e45b9bd166433ec121': [{'cmd': 'mdv2 colortables --filter=blue',
                                       'res': '$ mdv2 colortables '
                                              '--filter=blue\n'
                                              '\n'
                                              '\n'
                                              '\x1b[1;47;30m24 Bit (Web) '
                                              'Colors                                                             '
                                              '\x1b[0m\n'
                                              'CSS e.g. {color: rgb(255, 0, '
                                              '0)} or #F00 or hsl() or '
                                              'name...\n'
                                              'aliceblue           '
                                              'blue                '
                                              'blueviolet          '
                                              'cadetblue           \n'
                                              '\x1b[48;2;240;248;255m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;0;255m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;138;43;226m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;95;158;160m                   '
                                              '\x1b[0m \n'
                                              'cornflowerblue      '
                                              'darkblue            '
                                              'darkslateblue       '
                                              'deepskyblue         \n'
                                              '\x1b[48;2;100;149;237m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;0;139m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;72;61;139m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;191;255m                   '
                                              '\x1b[0m \n'
                                              'dodgerblue          '
                                              'lightblue           '
                                              'lightskyblue        '
                                              'lightsteelblue      \n'
                                              '\x1b[48;2;30;144;255m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;173;216;230m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;135;206;250m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;176;196;222m                   '
                                              '\x1b[0m \n'
                                              'mediumblue          '
                                              'mediumslateblue     '
                                              'midnightblue        '
                                              'powderblue          \n'
                                              '\x1b[48;2;0;0;205m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;123;104;238m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;25;25;112m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;176;224;230m                   '
                                              '\x1b[0m \n'
                                              'royalblue           '
                                              'skyblue             '
                                              'slateblue           '
                                              'steelblue           \n'
                                              '\x1b[48;2;65;105;225m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;135;206;235m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;106;90;205m                   '
                                              '\x1b[0m '
                                              '\x1b[48;2;70;130;180m                   '
                                              '\x1b[0m \n'
                                              '\n'
                                              '\n'
                                              '\x1b[1;47;30m8 Bit Colors '
                                              'Absolute                                                           '
                                              '\x1b[0m\n'
                                              'Config: color_table_256_true, '
                                              'then CSS: e.g. {color: '
                                              'ansi(9)})\n'
                                              'blue             '
                                              'navyblue         '
                                              'darkblue         '
                                              'blue3            \n'
                                              '\x1b[48;2;0;0;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;0;95m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;0;135m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;0;215m                '
                                              '\x1b[0m \n'
                                              'blue1            '
                                              'deepskyblue4     '
                                              'dodgerblue3      '
                                              'dodgerblue2      \n'
                                              '\x1b[48;2;0;0;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;95;175m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;95;215m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;95;255m                '
                                              '\x1b[0m \n'
                                              'deepskyblue3     '
                                              'dodgerblue1      '
                                              'deepskyblue2     '
                                              'deepskyblue1     \n'
                                              '\x1b[48;2;0;135;215m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;135;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;175;215m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;0;175;255m                '
                                              '\x1b[0m \n'
                                              'blueviolet       '
                                              'slateblue3       '
                                              'royalblue1       '
                                              'steelblue        \n'
                                              '\x1b[48;2;95;0;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;95;95;215m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;95;95;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;95;135;175m                '
                                              '\x1b[0m \n'
                                              'steelblue3       '
                                              'cornflowerblue   '
                                              'cadetblue        '
                                              'skyblue3         \n'
                                              '\x1b[48;2;95;135;215m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;95;135;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;95;175;175m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;95;175;215m                '
                                              '\x1b[0m \n'
                                              'steelblue1       '
                                              'slateblue1       '
                                              'lightslateblue   '
                                              'lightskyblue3    \n'
                                              '\x1b[48;2;95;215;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;135;95;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;135;135;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;135;175;215m                '
                                              '\x1b[0m \n'
                                              'skyblue2         '
                                              'skyblue1         '
                                              'lightsteelblue3  '
                                              'lightsteelblue   \n'
                                              '\x1b[48;2;135;175;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;135;215;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;175;175;215m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;175;175;255m                '
                                              '\x1b[0m \n'
                                              'lightskyblue1    '
                                              'lightsteelblue1  \n'
                                              '\x1b[48;2;175;215;255m                '
                                              '\x1b[0m '
                                              '\x1b[48;2;215;215;255m                '
                                              '\x1b[0m \n'
                                              '\n'
                                              '\n'
                                              '\x1b[1;47;30m8 Bit Colors, 0-15 '
                                              'Themable                                                     '
                                              '\x1b[0m\n'
                                              'CSS: {color: ansi(<0-255>)}\n'
                                              'blue             '
                                              'navyblue         '
                                              'darkblue         '
                                              'blue3            \n'
                                              '\x1b[48;5;12m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;17m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;18m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;20m                '
                                              '\x1b[0m \n'
                                              'blue1            '
                                              'deepskyblue4     '
                                              'dodgerblue3      '
                                              'dodgerblue2      \n'
                                              '\x1b[48;5;21m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;25m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;26m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;27m                '
                                              '\x1b[0m \n'
                                              'deepskyblue3     '
                                              'dodgerblue1      '
                                              'deepskyblue2     '
                                              'deepskyblue1     \n'
                                              '\x1b[48;5;32m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;33m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;38m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;39m                '
                                              '\x1b[0m \n'
                                              'blueviolet       '
                                              'slateblue3       '
                                              'royalblue1       '
                                              'steelblue        \n'
                                              '\x1b[48;5;57m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;62m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;63m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;67m                '
                                              '\x1b[0m \n'
                                              'steelblue3       '
                                              'cornflowerblue   '
                                              'cadetblue        '
                                              'skyblue3         \n'
                                              '\x1b[48;5;68m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;69m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;73m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;74m                '
                                              '\x1b[0m \n'
                                              'steelblue1       '
                                              'slateblue1       '
                                              'lightslateblue   '
                                              'lightskyblue3    \n'
                                              '\x1b[48;5;81m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;99m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;105m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;110m                '
                                              '\x1b[0m \n'
                                              'skyblue2         '
                                              'skyblue1         '
                                              'lightsteelblue3  '
                                              'lightsteelblue   \n'
                                              '\x1b[48;5;111m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;117m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;146m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;147m                '
                                              '\x1b[0m \n'
                                              'lightskyblue1    '
                                              'lightsteelblue1  \n'
                                              '\x1b[48;5;153m                '
                                              '\x1b[0m '
                                              '\x1b[48;5;189m                '
                                              '\x1b[0m \n'
                                              '\n'
                                              '\n'
                                              '\x1b[1;47;30m3/4 Bit '
                                              'Colors                                                                  '
                                              '\x1b[0m\n'
                                              'CSS: {color: ansi("<30-37>")}'}]}