{'cc7cfe5082f82fe5040d1507fcc56c19': [{'cmd': 'mdv2 -h',
                                       'res': '$ mdv2 -h\n'
                                              '\n'
                                              'Parameters:\n'
                                              '\n'
                                              '# mdv2\n'
                                              '- environ_prefix: MDV_\n'
                                              '## Logging\n'
                                              '- log_level: info\n'
                                              '## Markdown\n'
                                              '- rm_spaces: True\n'
                                              '- sample_text: # H1\n'
                                              'Hello *World!* from mdv!\n'
                                              '- tab_length: 4\n'
                                              '## Output\n'
                                              '- html_out: None\n'
                                              '- ruler: None\n'
                                              '- term_out: None\n'
                                              '## Plugins\n'
                                              '- boxes: term_css_boxes\n'
                                              '- color: term_color\n'
                                              '- colors_256: color_table_256\n'
                                              '- colors_web: color_table_web\n'
                                              '- conf: mdv_conf\n'
                                              '- log: structlog\n'
                                              '- mdparser: pymarkdown\n'
                                              '- render: term_render\n'
                                              '- style: term_css_style\n'
                                              '- textmaps: '
                                              'term_font_textmaps.py\n'
                                              '- theme: theme_base16\n'
                                              '- tree_analyzer: '
                                              'html_beautifulsoup\n'
                                              '### Actions\n'
                                              '- colortables: colortables\n'
                                              '- help: help\n'
                                              '- view: view\n'
                                              '## Styling\n'
                                              '- css_file: \n'
                                              "- inline_tags: ['em', 'strong', "
                                              "'b', 'code', 'del', 'super', "
                                              "'sub']\n"
                                              '- theme: theme_base16\n'
                                              '### CSS\n'
                                              "- BQ: {'border': '2 solid H1'}\n"
                                              "- OL: {'padding': 2}\n"
                                              "- UL: {'padding': 2}\n"
                                              '### Variables\n'
                                              '#### Admonitions\n'
                                              '- attention: H1\n'
                                              '- caution: H2\n'
                                              '- danger: R\n'
                                              '- dev: H5\n'
                                              '- hint: H4\n'
                                              '- note: H3\n'
                                              '- question: H5\n'
                                              '- summary: H1\n'
                                              '- warning: R\n'
                                              '#### Cells\n'
                                              '- BG: 30\n'
                                              '- BGL: 30\n'
                                              '- C: 3;100;97\n'
                                              '- CH1: 1;33\n'
                                              '- CH2: 1;32\n'
                                              '- CH3: 1;35\n'
                                              '- CH4: 1;35\n'
                                              '- CH5: 1;34\n'
                                              '- D: \n'
                                              '- EM: 3;31\n'
                                              '- H1: 1;33\n'
                                              '- H2: 1;32\n'
                                              '- H3: 1;35\n'
                                              '- H4: 1;35\n'
                                              '- H5: 1;34\n'
                                              '- L: 2;90\n'
                                              '- R: 31\n'
                                              '- STRONG: 1;32;41\n'
                                              '- T: 36\n'
                                              '#### Code\n'
                                              '- def_lexer: python\n'
                                              '- guess_lexer: True\n'
                                              '##### Highlight\n'
                                              '- Comment: L\n'
                                              '- Error: R\n'
                                              '- Generic: CH2\n'
                                              '- Keyword: CH3\n'
                                              '- Name: CH1\n'
                                              '- Number: CH4\n'
                                              '- Operator: CH5\n'
                                              '- String: CH4\n'
                                              '#### Text\n'
                                              '- bquote_pref: |\n'
                                              '- code_pref: | \n'
                                              '- hr_ends: ◈\n'
                                              '- hr_sep: ─\n'
                                              '- list_pref: - \n'
                                              '- txt_block_cut: ✂\n'
                                              '## Terminal\n'
                                              '- height: 0\n'
                                              '- height_default: 24\n'
                                              '- true_color: True\n'
                                              '- width: 0\n'
                                              '- width_default: 80\n'
                                              '## Actions\n'
                                              '- colortables: colortables\n'
                                              '- help: help\n'
                                              '- view: view\n'
                                              '\n'
                                              'Actions:\n'
                                              '\n'
                                              'Action:  colortables\n'
                                              '\n'
                                              'Produces color tables on '
                                              'stdout\n'
                                              '\n'
                                              '\n'
                                              '    Displays Various '
                                              'Colortables on stdout\n'
                                              '\n'
                                              '    - filter: When supplied we '
                                              'skip non matching entries. If a '
                                              "title matches we don't\n"
                                              '      display the others but '
                                              'all colors within the matching '
                                              'table.\n'
                                              '    - max: Maximum entries '
                                              'displayed per table\n'
                                              '    \n'
                                              'Action:  view\n'
                                              '\n'
                                              '\n'
                                              '    Renders the source\n'
                                              '\n'
                                              '    :param dflt_out [str]: API '
                                              "calls supply '' in order to "
                                              'supress printing.\n'
                                              '\n'
                                              '    Returns the rendered html, '
                                              'as list of rows.'}]}