{'071b6bc18d71660bd72f0ca22fc7aeb0': {'formatted': '\n'
                                                   '=== "Code"\n'
                                                   '\n'
                                                   '    ```python\n'
                                                   '    class '
                                                   'Plugins(DevPlugins):\n'
                                                   '        def '
                                                   '__getattr__(self, '
                                                   'plug_name):\n'
                                                   '            """only called '
                                                   'at a miss. -> ideal to '
                                                   'lazy import"""\n'
                                                   '            # the first '
                                                   "plugin is 'conf', called "
                                                   'in main, populating the '
                                                   'conf dict from config\n'
                                                   '            # file in '
                                                   "user's conf dir or mdv pkg "
                                                   '-> after this we know all '
                                                   'configurable kvs\n'
                                                   '            # plus we know '
                                                   'which action the user '
                                                   'called (default: view), '
                                                   'whichhh will be\n'
                                                   '            if plug_name '
                                                   "== 'conf':\n"
                                                   '                '
                                                   'set_sys_path_and_load_config()\n'
                                                   '            # '
                                                   'FileConfig[0] is from the '
                                                   'config file, listing all '
                                                   'available plugins by '
                                                   'name:\n'
                                                   '            filename = '
                                                   'getattr(FileConfig[0].Plugins, '
                                                   'plug_name, plug_name)\n'
                                                   '            # import it '
                                                   'and run the post_import '
                                                   'hook if present:\n'
                                                   '            return '
                                                   'load_plugin(plug_name, '
                                                   'filename)\n'
                                                   '    ```\n'
                                                   '\n'
                                                   '=== '
                                                   '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L107)"\n'
                                                   '    '
                                                   'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L107\n',
                                      'res': '\n'
                                             '=== "Code"\n'
                                             '\n'
                                             '    ```python\n'
                                             '    class Plugins(DevPlugins):\n'
                                             '        def __getattr__(self, '
                                             'plug_name):\n'
                                             '            """only called at a '
                                             'miss. -> ideal to lazy '
                                             'import"""\n'
                                             '            # the first plugin '
                                             "is 'conf', called in main, "
                                             'populating the conf dict from '
                                             'config\n'
                                             "            # file in user's "
                                             'conf dir or mdv pkg -> after '
                                             'this we know all configurable '
                                             'kvs\n'
                                             '            # plus we know which '
                                             'action the user called (default: '
                                             'view), whichhh will be\n'
                                             '            if plug_name == '
                                             "'conf':\n"
                                             '                '
                                             'set_sys_path_and_load_config()\n'
                                             '            # FileConfig[0] is '
                                             'from the config file, listing '
                                             'all available plugins by name:\n'
                                             '            filename = '
                                             'getattr(FileConfig[0].Plugins, '
                                             'plug_name, plug_name)\n'
                                             '            # import it and run '
                                             'the post_import hook if '
                                             'present:\n'
                                             '            return '
                                             'load_plugin(plug_name, '
                                             'filename)\n'
                                             '    ```\n'
                                             '\n'
                                             '=== '
                                             '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L107)"\n'
                                             '    '
                                             'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L107\n'},
 '4629c7e48545673c8809572845acb765': {'formatted': '\n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   '| name | module |\n'
                                                   '|-|-|\n'
                                                   '| '
                                                   '[boxes](./plugs/boxes.md) '
                                                   '| '
                                                   '[term_css_boxes](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_boxes.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[color](./plugs/color.md) '
                                                   '| '
                                                   '[color](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[colors_256](./plugs/colors_256.md) '
                                                   '| '
                                                   '[color_table_256](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_256.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[colors_web](./plugs/colors_web.md) '
                                                   '| '
                                                   '[color_table_web](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_web.py#L1) '
                                                   '|\n'
                                                   '| [conf](./plugs/conf.md) '
                                                   '| '
                                                   '[mdv_conf](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/mdv_conf.py#L1) '
                                                   '|\n'
                                                   '| [log](./plugs/log.md) | '
                                                   '[structlog](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/structlog.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[mdparser](./plugs/mdparser.md) '
                                                   '| '
                                                   '[pymarkdown](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/pymarkdown.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[render](./plugs/render.md) '
                                                   '| '
                                                   '[term_render](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_render.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[style](./plugs/style.md) '
                                                   '| '
                                                   '[term_css_style](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_style.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[textmaps](./plugs/textmaps.md) '
                                                   '| '
                                                   '[term_font_textmaps.py](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_font_textmaps.py.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[theme](./plugs/theme.md) '
                                                   '| '
                                                   '[theme_base16](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/theme_base16.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[tree_analyzer](./plugs/tree_analyzer.md) '
                                                   '| '
                                                   '[html_beautifulsoup](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/html_beautifulsoup.py#L1) '
                                                   '|\n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   'Action Plugins:  \n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   '| name | module |\n'
                                                   '|-|-|\n'
                                                   '| '
                                                   '[colortables](./plugs/colortables.md) '
                                                   '| '
                                                   '[colortables](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/colortables.py#L1) '
                                                   '|\n'
                                                   '| [help](./plugs/help.md) '
                                                   '| '
                                                   '[help](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/help.py#L1) '
                                                   '|\n'
                                                   '| [view](./plugs/view.md) '
                                                   '| '
                                                   '[view](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/view.py#L1) '
                                                   '|',
                                      'res': '\n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             '| name | module |\n'
                                             '|-|-|\n'
                                             '| [boxes](./plugs/boxes.md) | '
                                             '[term_css_boxes](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_boxes.py#L1) '
                                             '|\n'
                                             '| [color](./plugs/color.md) | '
                                             '[color](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color.py#L1) '
                                             '|\n'
                                             '| '
                                             '[colors_256](./plugs/colors_256.md) '
                                             '| '
                                             '[color_table_256](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_256.py#L1) '
                                             '|\n'
                                             '| '
                                             '[colors_web](./plugs/colors_web.md) '
                                             '| '
                                             '[color_table_web](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_web.py#L1) '
                                             '|\n'
                                             '| [conf](./plugs/conf.md) | '
                                             '[mdv_conf](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/mdv_conf.py#L1) '
                                             '|\n'
                                             '| [log](./plugs/log.md) | '
                                             '[structlog](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/structlog.py#L1) '
                                             '|\n'
                                             '| '
                                             '[mdparser](./plugs/mdparser.md) '
                                             '| '
                                             '[pymarkdown](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/pymarkdown.py#L1) '
                                             '|\n'
                                             '| [render](./plugs/render.md) | '
                                             '[term_render](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_render.py#L1) '
                                             '|\n'
                                             '| [style](./plugs/style.md) | '
                                             '[term_css_style](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_style.py#L1) '
                                             '|\n'
                                             '| '
                                             '[textmaps](./plugs/textmaps.md) '
                                             '| '
                                             '[term_font_textmaps.py](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_font_textmaps.py.py#L1) '
                                             '|\n'
                                             '| [theme](./plugs/theme.md) | '
                                             '[theme_base16](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/theme_base16.py#L1) '
                                             '|\n'
                                             '| '
                                             '[tree_analyzer](./plugs/tree_analyzer.md) '
                                             '| '
                                             '[html_beautifulsoup](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/html_beautifulsoup.py#L1) '
                                             '|\n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             'Action Plugins:  \n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             '| name | module |\n'
                                             '|-|-|\n'
                                             '| '
                                             '[colortables](./plugs/colortables.md) '
                                             '| '
                                             '[colortables](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/colortables.py#L1) '
                                             '|\n'
                                             '| [help](./plugs/help.md) | '
                                             '[help](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/help.py#L1) '
                                             '|\n'
                                             '| [view](./plugs/view.md) | '
                                             '[view](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/view.py#L1) '
                                             '|'},
 '5546c133050ca68dca5901f90e562895': {'formatted': '![](img/k1.svg)',
                                      'res': '![](img/k1.svg)'},
 '732c541802dffaac825db709b70c8739': {'formatted': '\n'
                                                   '=== "Code"\n'
                                                   '\n'
                                                   '    ```python\n'
                                                   '    class Plugins:\n'
                                                   '    \n'
                                                   '        boxes          = '
                                                   "'term_css_boxes'\n"
                                                   '        color          = '
                                                   "'color'\n"
                                                   '        colors_256     = '
                                                   "'color_table_256'\n"
                                                   '        colors_web     = '
                                                   "'color_table_web'\n"
                                                   '        conf           = '
                                                   "'mdv_conf'\n"
                                                   '        log            = '
                                                   "'structlog'\n"
                                                   '        mdparser       = '
                                                   "'pymarkdown'\n"
                                                   '        render         = '
                                                   "'term_render'\n"
                                                   '        style          = '
                                                   "'term_css_style'\n"
                                                   '        textmaps       = '
                                                   "'term_font_textmaps.py'\n"
                                                   '        theme          = '
                                                   "'theme_base16'\n"
                                                   '        tree_analyzer  = '
                                                   "'html_beautifulsoup'\n"
                                                   '    \n'
                                                   '        class Actions:\n'
                                                   '            colortables= '
                                                   "'colortables'\n"
                                                   '            view       = '
                                                   "'view'\n"
                                                   '            help       = '
                                                   "'help'\n"
                                                   '    ```\n'
                                                   '\n'
                                                   '=== '
                                                   '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/config.py#L5)"\n'
                                                   '    '
                                                   'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/config.py#L5\n',
                                      'res': '\n'
                                             '=== "Code"\n'
                                             '\n'
                                             '    ```python\n'
                                             '    class Plugins:\n'
                                             '    \n'
                                             '        boxes          = '
                                             "'term_css_boxes'\n"
                                             '        color          = '
                                             "'color'\n"
                                             '        colors_256     = '
                                             "'color_table_256'\n"
                                             '        colors_web     = '
                                             "'color_table_web'\n"
                                             '        conf           = '
                                             "'mdv_conf'\n"
                                             '        log            = '
                                             "'structlog'\n"
                                             '        mdparser       = '
                                             "'pymarkdown'\n"
                                             '        render         = '
                                             "'term_render'\n"
                                             '        style          = '
                                             "'term_css_style'\n"
                                             '        textmaps       = '
                                             "'term_font_textmaps.py'\n"
                                             '        theme          = '
                                             "'theme_base16'\n"
                                             '        tree_analyzer  = '
                                             "'html_beautifulsoup'\n"
                                             '    \n'
                                             '        class Actions:\n'
                                             '            colortables= '
                                             "'colortables'\n"
                                             "            view       = 'view'\n"
                                             "            help       = 'help'\n"
                                             '    ```\n'
                                             '\n'
                                             '=== '
                                             '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/config.py#L5)"\n'
                                             '    '
                                             'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/config.py#L5\n'},
 '81b9e14748c13e74449a8be17ce1709d': {'formatted': '\n'
                                                   '=== "Code"\n'
                                                   '\n'
                                                   '    ```python\n'
                                                   '    def main():\n'
                                                   '        # not sure if we '
                                                   'are able to support py2 '
                                                   'but this is obligatory in '
                                                   'any case:\n'
                                                   '        if not PY3:\n'
                                                   '            '
                                                   'fix_py2_default_encoding()\n'
                                                   '        # conf (default: '
                                                   'mdv_conf.py) is a must '
                                                   'have plugin:\n'
                                                   '        # 1. plugins.conf '
                                                   'imports it (getattr hook)\n'
                                                   '        # .configure '
                                                   'populates the tools.C dict '
                                                   'with all values from file, '
                                                   'env, cli\n'
                                                   '        # .run runs all '
                                                   'action functions (default: '
                                                   'view)\n'
                                                   '        '
                                                   'plugins.conf.configure(argv=list(sys.argv)).run()\n'
                                                   '    ```\n'
                                                   '\n'
                                                   '=== '
                                                   '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8)"\n'
                                                   '    '
                                                   'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8\n',
                                      'res': '\n'
                                             '=== "Code"\n'
                                             '\n'
                                             '    ```python\n'
                                             '    def main():\n'
                                             '        # not sure if we are '
                                             'able to support py2 but this is '
                                             'obligatory in any case:\n'
                                             '        if not PY3:\n'
                                             '            '
                                             'fix_py2_default_encoding()\n'
                                             '        # conf (default: '
                                             'mdv_conf.py) is a must have '
                                             'plugin:\n'
                                             '        # 1. plugins.conf '
                                             'imports it (getattr hook)\n'
                                             '        # .configure populates '
                                             'the tools.C dict with all values '
                                             'from file, env, cli\n'
                                             '        # .run runs all action '
                                             'functions (default: view)\n'
                                             '        '
                                             'plugins.conf.configure(argv=list(sys.argv)).run()\n'
                                             '    ```\n'
                                             '\n'
                                             '=== '
                                             '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8)"\n'
                                             '    '
                                             'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8\n'},
 '81b9e14748c13e74449a8be17ce1709d_': {'formatted': '\n'
                                                    '=== "Code"\n'
                                                    '\n'
                                                    '    ```python\n'
                                                    '    def main():\n'
                                                    '        # not sure if we '
                                                    'are able to support py2 '
                                                    'but this is obligatory in '
                                                    'any case:\n'
                                                    '        if not PY3:\n'
                                                    '            '
                                                    'fix_py2_default_encoding()\n'
                                                    '        # conf (default: '
                                                    'mdv_conf.py) is a must '
                                                    'have plugin:\n'
                                                    '        # 1. plugins.conf '
                                                    'imports it (getattr '
                                                    'hook)\n'
                                                    '        # .configure '
                                                    'populates the tools.C '
                                                    'dict with all values from '
                                                    'file, env, cli\n'
                                                    '        # .run runs all '
                                                    'action functions '
                                                    '(default: view)\n'
                                                    '        '
                                                    'plugins.conf.configure(argv=list(sys.argv)).run()\n'
                                                    '    ```\n'
                                                    '\n'
                                                    '=== '
                                                    '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8)"\n'
                                                    '    '
                                                    'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8\n',
                                       'res': '\n'
                                              '=== "Code"\n'
                                              '\n'
                                              '    ```python\n'
                                              '    def main():\n'
                                              '        # not sure if we are '
                                              'able to support py2 but this is '
                                              'obligatory in any case:\n'
                                              '        if not PY3:\n'
                                              '            '
                                              'fix_py2_default_encoding()\n'
                                              '        # conf (default: '
                                              'mdv_conf.py) is a must have '
                                              'plugin:\n'
                                              '        # 1. plugins.conf '
                                              'imports it (getattr hook)\n'
                                              '        # .configure populates '
                                              'the tools.C dict with all '
                                              'values from file, env, cli\n'
                                              '        # .run runs all action '
                                              'functions (default: view)\n'
                                              '        '
                                              'plugins.conf.configure(argv=list(sys.argv)).run()\n'
                                              '    ```\n'
                                              '\n'
                                              '=== '
                                              '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8)"\n'
                                              '    '
                                              'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L8\n'}}