{'071b6bc18d71660bd72f0ca22fc7aeb0': {'formatted': '\n'
                                                   '=== "Code"\n'
                                                   '\n'
                                                   '    ```python\n'
                                                   '    class '
                                                   'Plugins(DevPlugins):\n'
                                                   '        def '
                                                   '__getattr__(self, '
                                                   'plug_name):\n'
                                                   '            """only called '
                                                   'at a miss. -> ideal to '
                                                   'lazy import"""\n'
                                                   '    \n'
                                                   '            try:\n'
                                                   '                if '
                                                   "plug_name != 'config':  # "
                                                   "raises for 'config', "
                                                   'preventing loops\n'
                                                   '                    P = '
                                                   'plugins.config.Plugins  # '
                                                   'will import config the '
                                                   'first time\n'
                                                   '                filename = '
                                                   'getattr(P, plug_name)\n'
                                                   '            except '
                                                   'Exception as ex:\n'
                                                   '                # '
                                                   'different config format, '
                                                   'no mapping - try the name '
                                                   'as given, allowing:\n'
                                                   '                # the user '
                                                   'to just add an action '
                                                   'module and call it on the '
                                                   'CLI by name:\n'
                                                   '                filename = '
                                                   'plug_name\n'
                                                   '    \n'
                                                   '            # import it '
                                                   'and run the post_import '
                                                   'hook if present:\n'
                                                   '            return '
                                                   'load_plugin(plug_name, '
                                                   'filename)\n'
                                                   '    ```\n'
                                                   '\n'
                                                   '=== '
                                                   '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L103)"\n'
                                                   '    '
                                                   'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L103\n',
                                      'res': '\n'
                                             '=== "Code"\n'
                                             '\n'
                                             '    ```python\n'
                                             '    class Plugins(DevPlugins):\n'
                                             '        def __getattr__(self, '
                                             'plug_name):\n'
                                             '            """only called at a '
                                             'miss. -> ideal to lazy '
                                             'import"""\n'
                                             '    \n'
                                             '            try:\n'
                                             '                if plug_name != '
                                             "'config':  # raises for "
                                             "'config', preventing loops\n"
                                             '                    P = '
                                             'plugins.config.Plugins  # will '
                                             'import config the first time\n'
                                             '                filename = '
                                             'getattr(P, plug_name)\n'
                                             '            except Exception as '
                                             'ex:\n'
                                             '                # different '
                                             'config format, no mapping - try '
                                             'the name as given, allowing:\n'
                                             '                # the user to '
                                             'just add an action module and '
                                             'call it on the CLI by name:\n'
                                             '                filename = '
                                             'plug_name\n'
                                             '    \n'
                                             '            # import it and run '
                                             'the post_import hook if '
                                             'present:\n'
                                             '            return '
                                             'load_plugin(plug_name, '
                                             'filename)\n'
                                             '    ```\n'
                                             '\n'
                                             '=== '
                                             '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L103)"\n'
                                             '    '
                                             'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugs.py#L103\n'},
 '4396e8762211f578d6a16cf9c030470f': {'formatted': '![](img/k1.svg)',
                                      'res': '![](img/k1.svg)'},
 '5c0bdec05e0b6a5f54d1591b3f286eff': {'formatted': '\n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   'Action Plugins:  \n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   '| functional name | module '
                                                   'name |\n'
                                                   '|-|-|\n'
                                                   '| '
                                                   '[colortables](./plugs/colortables.md) '
                                                   '| '
                                                   '[colortables](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/colortables.py#L1) '
                                                   '|\n'
                                                   '| [help](./plugs/help.md) '
                                                   '| '
                                                   '[help](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/help.py#L1) '
                                                   '|\n'
                                                   '| [view](./plugs/view.md) '
                                                   '| '
                                                   '[view](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/view.py#L1) '
                                                   '|\n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   'Other Plugins:  \n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   '| functional name | module '
                                                   'name |\n'
                                                   '|-|-|\n'
                                                   '| '
                                                   '[boxes](./plugs/boxes.md) '
                                                   '| '
                                                   '[term_css_boxes](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_boxes.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[color](./plugs/color.md) '
                                                   '| '
                                                   '[term_color](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_color.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[colors_256](./plugs/colors_256.md) '
                                                   '| '
                                                   '[color_table_256](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_256.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[colors_web](./plugs/colors_web.md) '
                                                   '| '
                                                   '[color_table_web](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_web.py#L1) '
                                                   '|\n'
                                                   '| [conf](./plugs/conf.md) '
                                                   '| '
                                                   '[mdv_conf](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/mdv_conf.py#L1) '
                                                   '|\n'
                                                   '| [log](./plugs/log.md) | '
                                                   '[structlog](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/structlog.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[mdparser](./plugs/mdparser.md) '
                                                   '| '
                                                   '[pymarkdown](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/pymarkdown.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[render](./plugs/render.md) '
                                                   '| '
                                                   '[term_render](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_render.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[style](./plugs/style.md) '
                                                   '| '
                                                   '[term_css_style](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_style.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[textmaps](./plugs/textmaps.md) '
                                                   '| '
                                                   '[term_font_textmaps.py](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_font_textmaps.py.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[theme](./plugs/theme.md) '
                                                   '| '
                                                   '[theme_base16](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/theme_base16.py#L1) '
                                                   '|\n'
                                                   '| '
                                                   '[tree_analyzer](./plugs/tree_analyzer.md) '
                                                   '| '
                                                   '[html_beautifulsoup](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/html_beautifulsoup.py#L1) '
                                                   '|\n'
                                                   '| (mdv config file) | '
                                                   '[config](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/config.py#L1) '
                                                   '|',
                                      'res': '\n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             'Action Plugins:  \n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             '| functional name | module name '
                                             '|\n'
                                             '|-|-|\n'
                                             '| '
                                             '[colortables](./plugs/colortables.md) '
                                             '| '
                                             '[colortables](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/colortables.py#L1) '
                                             '|\n'
                                             '| [help](./plugs/help.md) | '
                                             '[help](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/help.py#L1) '
                                             '|\n'
                                             '| [view](./plugs/view.md) | '
                                             '[view](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/view.py#L1) '
                                             '|\n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             'Other Plugins:  \n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             '| functional name | module name '
                                             '|\n'
                                             '|-|-|\n'
                                             '| [boxes](./plugs/boxes.md) | '
                                             '[term_css_boxes](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_boxes.py#L1) '
                                             '|\n'
                                             '| [color](./plugs/color.md) | '
                                             '[term_color](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_color.py#L1) '
                                             '|\n'
                                             '| '
                                             '[colors_256](./plugs/colors_256.md) '
                                             '| '
                                             '[color_table_256](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_256.py#L1) '
                                             '|\n'
                                             '| '
                                             '[colors_web](./plugs/colors_web.md) '
                                             '| '
                                             '[color_table_web](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/color_table_web.py#L1) '
                                             '|\n'
                                             '| [conf](./plugs/conf.md) | '
                                             '[mdv_conf](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/mdv_conf.py#L1) '
                                             '|\n'
                                             '| [log](./plugs/log.md) | '
                                             '[structlog](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/structlog.py#L1) '
                                             '|\n'
                                             '| '
                                             '[mdparser](./plugs/mdparser.md) '
                                             '| '
                                             '[pymarkdown](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/pymarkdown.py#L1) '
                                             '|\n'
                                             '| [render](./plugs/render.md) | '
                                             '[term_render](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_render.py#L1) '
                                             '|\n'
                                             '| [style](./plugs/style.md) | '
                                             '[term_css_style](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_css_style.py#L1) '
                                             '|\n'
                                             '| '
                                             '[textmaps](./plugs/textmaps.md) '
                                             '| '
                                             '[term_font_textmaps.py](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/term_font_textmaps.py.py#L1) '
                                             '|\n'
                                             '| [theme](./plugs/theme.md) | '
                                             '[theme_base16](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/theme_base16.py#L1) '
                                             '|\n'
                                             '| '
                                             '[tree_analyzer](./plugs/tree_analyzer.md) '
                                             '| '
                                             '[html_beautifulsoup](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/html_beautifulsoup.py#L1) '
                                             '|\n'
                                             '| (mdv config file) | '
                                             '[config](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/plugins/config.py#L1) '
                                             '|'},
 '81b9e14748c13e74449a8be17ce1709d': {'formatted': '\n'
                                                   '=== "Code"\n'
                                                   '\n'
                                                   '    ```python\n'
                                                   '    def main(argv=None):\n'
                                                   '        argv = argv or '
                                                   'list(sys.argv)\n'
                                                   '        # not sure if we '
                                                   'are able to support py2 '
                                                   'but this is obligatory in '
                                                   'any case:\n'
                                                   '        if not PY3:\n'
                                                   '            '
                                                   'fix_py2_default_encoding()\n'
                                                   '        '
                                                   'sys_path_add_user_conf_dir(argv)\n'
                                                   '        # conf (default: '
                                                   'mdv_conf.py) is a must '
                                                   'have plugin:\n'
                                                   '        # 1. plugins.conf '
                                                   'imports it (getattr hook)\n'
                                                   '        # .configure '
                                                   'populates the tools.C dict '
                                                   'with all values from file, '
                                                   'env, cli\n'
                                                   '        # .run runs all '
                                                   'action functions (default: '
                                                   'view)\n'
                                                   '        '
                                                   'plugins.conf.configure(argv=argv)\n'
                                                   '        '
                                                   'plugins.conf.run()\n'
                                                   '    ```\n'
                                                   '\n'
                                                   '=== '
                                                   '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L28)"\n'
                                                   '    '
                                                   'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L28\n',
                                      'res': '\n'
                                             '=== "Code"\n'
                                             '\n'
                                             '    ```python\n'
                                             '    def main(argv=None):\n'
                                             '        argv = argv or '
                                             'list(sys.argv)\n'
                                             '        # not sure if we are '
                                             'able to support py2 but this is '
                                             'obligatory in any case:\n'
                                             '        if not PY3:\n'
                                             '            '
                                             'fix_py2_default_encoding()\n'
                                             '        '
                                             'sys_path_add_user_conf_dir(argv)\n'
                                             '        # conf (default: '
                                             'mdv_conf.py) is a must have '
                                             'plugin:\n'
                                             '        # 1. plugins.conf '
                                             'imports it (getattr hook)\n'
                                             '        # .configure populates '
                                             'the tools.C dict with all values '
                                             'from file, env, cli\n'
                                             '        # .run runs all action '
                                             'functions (default: view)\n'
                                             '        '
                                             'plugins.conf.configure(argv=argv)\n'
                                             '        plugins.conf.run()\n'
                                             '    ```\n'
                                             '\n'
                                             '=== '
                                             '"[:fontawesome-brands-git-alt:](https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L28)"\n'
                                             '    '
                                             'https://github.com/AXGKl/terminal_markdown_viewer/blob/master/src/mdv/cli.py#L28\n'}}